-- Generated by xflowd migrate tsdb-tags (Phase C § C2)
-- SPEC-DEVICE-IDENTITY-001 — device_id (composite) -> uid (UUID) backfill
--
-- IMPORTANT (InfluxDB v3 backfill):
--   - InfluxDB v3 has NO native UPDATE for tags.
--   - This script SELECTs affected rows. Operator MUST re-write rows
--     with additional 'uid' tag using line-protocol (influx3 CLI / API).
--   - See RUN.md (in this output directory) for detailed procedure.
--   - Run in STAGING first.
--
-- Generated at: 2026-05-26T10:30:00Z
-- Target: InfluxDB v3 (SQL / InfluxQL)
-- Database: xflow
--
-- Mappings: 3 composite -> uid pairs

-- Backfill: device_id "century:7" -> uid "d8e7f99b-8074-4e6f-c051-af6fbd4e5f60"
-- Affected measurements: outdoor_temp
-- Tag key: "device_id"
-- Step 1: Identify affected rows (review before re-writing with uid tag).
SELECT * FROM "outdoor_temp" WHERE "device_id" = 'century:7';

-- Backfill: device_id "lgcnp:81" -> uid "a58ba668-5741-4b3c-9d2e-7f3c8a1b2c3d"
-- Affected measurements: indoor_temp, outdoor_temp
-- Tag key: "device_id"
-- Step 1: Identify affected rows (review before re-writing with uid tag).
SELECT * FROM "indoor_temp" WHERE "device_id" = 'lgcnp:81';
SELECT * FROM "outdoor_temp" WHERE "device_id" = 'lgcnp:81';

-- Backfill: device_id "lgcnp:82" -> uid "b6c5d779-6852-4c4d-ae3f-8f4d9b2c3d4e"
-- Affected measurements: indoor_temp
-- Tag key: "device_id"
-- Step 1: Identify affected rows (review before re-writing with uid tag).
SELECT * FROM "indoor_temp" WHERE "device_id" = 'lgcnp:82';

