// Generated by xflowd migrate tsdb-tags (Phase C § C2)
// SPEC-DEVICE-IDENTITY-001 — device_id (composite) → uid (UUID) backfill
//
// IMPORTANT:
//   - This script was AUTO-GENERATED. Review before execution.
//   - Run in STAGING first, then production after verification.
//   - Take an Influx backup (snapshot) before execution.
//   - Operator responsibility: monitor execution and verify result.
//
// Execution (example — adjust to your environment):
//
//   influx query --org <ORG> --token <TOKEN> --file migration-v2.flux
//
// Generated at: 2026-05-26T10:30:00Z
// Target: InfluxDB v2 (Flux)
// Bucket: xflow
// Org: acme
//
// Mappings: 3 composite → uid pairs

// Backfill: device_id "century:7" -> uid "d8e7f99b-8074-4e6f-c051-af6fbd4e5f60"
// Affected measurements: outdoor_temp
// Tag key: "device_id"
from(bucket: "xflow")
  |> range(start: 0)
  |> filter(fn: (r) => r["device_id"] == "century:7")
  |> map(fn: (r) => ({ r with uid: "d8e7f99b-8074-4e6f-c051-af6fbd4e5f60" }))
  |> to(bucket: "xflow")

// Backfill: device_id "lgcnp:81" -> uid "a58ba668-5741-4b3c-9d2e-7f3c8a1b2c3d"
// Affected measurements: indoor_temp, outdoor_temp
// Tag key: "device_id"
from(bucket: "xflow")
  |> range(start: 0)
  |> filter(fn: (r) => r["device_id"] == "lgcnp:81")
  |> map(fn: (r) => ({ r with uid: "a58ba668-5741-4b3c-9d2e-7f3c8a1b2c3d" }))
  |> to(bucket: "xflow")

// Backfill: device_id "lgcnp:82" -> uid "b6c5d779-6852-4c4d-ae3f-8f4d9b2c3d4e"
// Affected measurements: indoor_temp
// Tag key: "device_id"
from(bucket: "xflow")
  |> range(start: 0)
  |> filter(fn: (r) => r["device_id"] == "lgcnp:82")
  |> map(fn: (r) => ({ r with uid: "b6c5d779-6852-4c4d-ae3f-8f4d9b2c3d4e" }))
  |> to(bucket: "xflow")

