package samsung

import "errors"

var (
	ErrInvalidTransportType    = errors.New("samsung_hvacr01: invalid transport type")
	ErrSerialPortRequired      = errors.New("samsung_hvacr01: serial port path required")
	ErrTCPHostRequired         = errors.New("samsung_hvacr01: TCP host required")
	ErrTCPPortRequired         = errors.New("samsung_hvacr01: TCP port required")
	ErrDeviceNotFound          = errors.New("samsung_hvacr01: device not found")
	ErrInvalidMode             = errors.New("samsung_hvacr01: invalid operation mode")
	ErrInvalidFanSpeed         = errors.New("samsung_hvacr01: invalid fan speed")
	ErrTemperatureOutOfRange   = errors.New("samsung_hvacr01: temperature out of range (16.0-30.0)")
	ErrChecksumMismatch        = errors.New("samsung_hvacr01: CRC16-CCITT checksum mismatch")
	ErrProtocolParseFailed     = errors.New("samsung_hvacr01: protocol parse failed")
	ErrInvalidFrameSTX         = errors.New("samsung_hvacr01: invalid STX byte (expected 0x32)")
	ErrInvalidFrameETX         = errors.New("samsung_hvacr01: invalid ETX byte (expected 0x34)")
	ErrInvalidFrameLength      = errors.New("samsung_hvacr01: frame length mismatch")
	ErrInvalidAddress          = errors.New("samsung_hvacr01: invalid NASA address format")
	ErrInvalidMessageSetIndex  = errors.New("samsung_hvacr01: invalid message set index nibble")
	ErrDeviceOffline           = errors.New("samsung_hvacr01: device is offline")
	ErrDeviceNotReady          = errors.New("samsung_hvacr01: device not ready")
	ErrTransportNotConnected   = errors.New("samsung_hvacr01: transport not connected")
	ErrInvalidCommand          = errors.New("samsung_hvacr01: invalid command")
	ErrDeviceAlreadyRegistered = errors.New("samsung_hvacr01: device already registered")
	ErrConfigDeviceProtected   = errors.New("samsung_hvacr01: config-based device cannot be removed")
	ErrSequenceNumOverflow     = errors.New("samsung_hvacr01: sequence number overflow")
	ErrDeviceIDNotFound        = errors.New("samsung_hvacr01: device ID not found")
	ErrDuplicateDeviceID       = errors.New("samsung_hvacr01: duplicate device ID")
	ErrDevicePoweredOff        = errors.New("samsung_hvacr01: device is powered off, only power control is allowed")
)
