package samsung

// specified_device_id_test.go — SPEC: samsung add_device 지정 device_id 사용 버그 수정.
//
// 버그: add_device 의 device_id 파라미터가 dev.UnitID 에만 저장되고, 실제 device_id 는
// ResolveDeviceID(agent, addr.String()) 로 새 UUID 가 자동생성되어 지정값이 무시됐다.
// 수정: 지정 시 SetDeviceID(agent, 주소, 지정값) 로 (agent, 주소)→지정값을 등록해,
// 이후 ResolveDeviceID(agent, 주소) 가 지정값을 반환한다. 미지정 시 자동생성 보존.

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/xtra/xflow/internal/agent"
	"github.com/xtra/xflow/internal/storage"
)

// withMemoryDeviceIDRepo 는 실제 storage 메모리 저장소를 주입하고 종료 시 복원한다.
// (fake 대신 실제 Set 유일성/영속 로직을 구동하기 위함.)
func withMemoryDeviceIDRepo(t *testing.T) *storage.DeviceIDMemoryRepository {
	t.Helper()
	prev := agent.GetDeviceIDRepository()
	repo := storage.NewDeviceIDMemoryRepository()
	agent.SetDeviceIDRepository(repo)
	t.Cleanup(func() { agent.SetDeviceIDRepository(prev) })
	return repo
}

// TestProcessAddDevice_SpecifiedDeviceID 는 핵심 버그 재현/수정 검증이다.
// add_device 에 device_id 를 지정하면, 이후 (agent, 주소) 키의 ResolveDeviceID 가
// 지정값을 반환해야 한다. (수정 전에는 자동 UUID 가 나와 FAIL = 버그 재현.)
func TestProcessAddDevice_SpecifiedDeviceID(t *testing.T) {
	withMemoryDeviceIDRepo(t)
	a, _, _ := newTestAgent(t)

	resp, err := processJSON(t, a, map[string]any{
		"command":     "add_device",
		"address":     "200003",
		"device_id":   "my-fixed-id-123",
		"device_type": "HVACR.IDU",
	})
	require.NoError(t, err)
	require.Equal(t, "ok", resp["status"])

	addr, _ := ParseNasaAddress("200003")

	// 핵심: emit/telemetry 경로가 쓰는 (agent, 주소) 키로 지정값이 나와야 한다.
	got := agent.ResolveDeviceID(context.Background(), a.agentConfig.Name, addr.String())
	assert.Equal(t, "my-fixed-id-123", got,
		"ResolveDeviceID(agent, addr) must return the user-specified device_id")

	// add_device 응답의 device_id 도 지정값과 일치해야 한다(응답/emit 일관성).
	assert.Equal(t, "my-fixed-id-123", resp["device_id"],
		"add_device response device_id must equal the specified id")
}

// TestProcessAddDevice_AutoGenerated_NoRegression 은 device_id 미지정 시 기존
// 자동생성 UUID 동작이 그대로 보존됨을 검증한다(무회귀).
func TestProcessAddDevice_AutoGenerated_NoRegression(t *testing.T) {
	withMemoryDeviceIDRepo(t)
	a, _, _ := newTestAgent(t)

	resp, err := processJSON(t, a, map[string]any{
		"command":     "add_device",
		"address":     "200003",
		"device_type": "HVACR.IDU",
		// device_id 미지정
	})
	require.NoError(t, err)
	require.Equal(t, "ok", resp["status"])

	addr, _ := ParseNasaAddress("200003")
	got := agent.ResolveDeviceID(context.Background(), a.agentConfig.Name, addr.String())

	// 자동생성 UUID: 36자 UUID v4 형식, 지정값과 무관.
	assert.Len(t, got, 36, "unspecified device_id must auto-generate a UUID")
	assert.NotEqual(t, "my-fixed-id-123", got)
	assert.Equal(t, got, resp["device_id"], "response device_id must equal the auto-generated UUID")
}

// TestProcessAddDevice_DuplicateSpecifiedID 는 같은 지정 device_id 를 다른 주소에
// 추가하면 ErrDuplicateDeviceID 로 거부됨을 검증한다(유일성).
func TestProcessAddDevice_DuplicateSpecifiedID(t *testing.T) {
	withMemoryDeviceIDRepo(t)
	a, _, _ := newTestAgent(t)

	_, err := processJSON(t, a, map[string]any{
		"command":   "add_device",
		"address":   "200003",
		"device_id": "dup-id",
	})
	require.NoError(t, err)

	_, err = processJSON(t, a, map[string]any{
		"command":   "add_device",
		"address":   "200004",
		"device_id": "dup-id", // 다른 주소, 같은 지정 id
	})
	assert.ErrorIs(t, err, ErrDuplicateDeviceID)
}

// TestRestoreSpecifiedDeviceIDs_ConfigAuthoritativeOnRepoLoss 는 재시작 왕복을 검증한다.
// 지정 id 로 등록 → 영속(config) → 저장소 파일 유실 시뮬레이션(빈 저장소로 재구성) →
// restoreSpecifiedDeviceIDs 가 config 의 지정 id 를 복구해 device_id 가 유지된다.
func TestRestoreSpecifiedDeviceIDs_ConfigAuthoritativeOnRepoLoss(t *testing.T) {
	// 1) 원본 세션: 지정 id 등록.
	repo1 := withMemoryDeviceIDRepo(t)
	_ = repo1
	a1, _, _ := newTestAgent(t)
	_, err := processJSON(t, a1, map[string]any{
		"command":   "add_device",
		"address":   "200003",
		"device_id": "my-fixed-id-123",
	})
	require.NoError(t, err)

	addr, _ := ParseNasaAddress("200003")
	require.Equal(t, "my-fixed-id-123",
		agent.ResolveDeviceID(context.Background(), a1.agentConfig.Name, addr.String()))

	// 영속: config 에 저장될 UnitID(=지정 id)를 확인.
	persisted := a1.GetPersistableDevices()
	var found bool
	for _, e := range persisted {
		if e.Address == addr.String() {
			found = true
			require.Equal(t, "my-fixed-id-123", e.Name, "persisted UnitID must carry the specified id")
		}
	}
	require.True(t, found, "added device must be persistable")

	// 2) 재시작 + 저장소 파일 유실: 빈 새 저장소.
	prev := agent.GetDeviceIDRepository()
	agent.SetDeviceIDRepository(storage.NewDeviceIDMemoryRepository())
	t.Cleanup(func() { agent.SetDeviceIDRepository(prev) })

	// config 복원 시뮬레이션: 지정 id(UnitID) 를 가진 디바이스를 새 에이전트에 등록.
	a2, _, _ := newTestAgent(t) // 동일 agentConfig.Name
	a2.mu.Lock()
	a2.devices[addr] = &NasaDevice{
		Address:       addr,
		UnitID:        "my-fixed-id-123", // 복원된 지정 id
		Type:          "HVACR.IDU",
		Source:        "bridge",
		ReportEnabled: true,
	}
	a2.deviceIDs["my-fixed-id-123"] = addr
	a2.mu.Unlock()

	// 빈 저장소에 재등록 → config authoritative.
	a2.restoreSpecifiedDeviceIDs()

	got := agent.ResolveDeviceID(context.Background(), a2.agentConfig.Name, addr.String())
	assert.Equal(t, "my-fixed-id-123", got,
		"after restart with lost repo, config-specified device_id must be restored")
}

// TestRestoreSpecifiedDeviceIDs_PreservesExistingRepoEntry 는 저장소가 정상일 때
// 기존 device_id 를 restoreSpecifiedDeviceIDs 가 덮어쓰지 않음을 검증한다(무회귀).
// (set-if-absent: 기존 저장 디바이스의 device_id 를 바꾸지 않는다.)
func TestRestoreSpecifiedDeviceIDs_PreservesExistingRepoEntry(t *testing.T) {
	withMemoryDeviceIDRepo(t)
	a, _, _ := newTestAgent(t)

	addr, _ := ParseNasaAddress("200003")

	// 저장소에 이미 기존 UUID 가 있다(예: 이전 세션의 자동생성값).
	existing := agent.ResolveDeviceID(context.Background(), a.agentConfig.Name, addr.String())
	require.Len(t, existing, 36)

	// 같은 주소에 UnitID(다른 지정값)를 가진 디바이스가 config 로 복원됐다고 가정.
	a.mu.Lock()
	a.devices[addr] = &NasaDevice{
		Address: addr, UnitID: "different-specified", Type: "HVACR.IDU", Source: "config", ReportEnabled: true,
	}
	a.mu.Unlock()

	a.restoreSpecifiedDeviceIDs()

	// 저장소에 기존 값이 있었으므로 덮어쓰지 않아야 한다.
	got := agent.ResolveDeviceID(context.Background(), a.agentConfig.Name, addr.String())
	assert.Equal(t, existing, got,
		"restore must not overwrite an existing repo entry (set-if-absent)")
}
