// script_v2.go — InfluxDB v2 (Flux) backfill 스크립트 생성.
//
// 생성된 스크립트는 운영자가 `influx query --file <script.flux>` 형태로 실행한다.
// 도구는 절대 직접 실행하지 않는다 — 출력은 파일뿐.
//
// Flux 패턴:
//
//	from(bucket: "xflow")
//	  |> range(start: 0)
//	  |> filter(fn: (r) => r["device_id"] == "lgcnp:81")
//	  |> map(fn: (r) => ({ r with uid: "a58ba668-..." }))
//	  |> to(bucket: "xflow")
//
// 각 (composite → UUID) 매핑마다 하나의 query block 을 생성한다.
package tsdbtags

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// fluxScriptHeader 는 생성된 .flux 파일의 상단 주석 (운영자 안내).
const fluxScriptHeader = `// Generated by xflowd migrate tsdb-tags (Phase C § C2)
// SPEC-DEVICE-IDENTITY-001 — device_id (composite) → uid (UUID) backfill
//
// IMPORTANT:
//   - This script was AUTO-GENERATED. Review before execution.
//   - Run in STAGING first, then production after verification.
//   - Take an Influx backup (snapshot) before execution.
//   - Operator responsibility: monitor execution and verify result.
//
// Execution (example — adjust to your environment):
//
//   influx query --org <ORG> --token <TOKEN> --file migration-v2.flux
//
// Generated at: %s
// Target: InfluxDB v2 (Flux)
// Bucket: %s
// Org: %s
//
// Mappings: %d composite → uid pairs

`

// fluxQueryTemplate 는 단일 (composite, UUID) 변환을 위한 Flux 블록이다.
//
// `set()` 대신 `map(fn)` 을 사용하는 이유: set 은 빈 column 에만 값을 채우는 반면
// map 은 명시적으로 record 에 uid 필드를 부착한다. backfill 의도가 명확해진다.
//
// `to()` 는 동일 bucket 에 다시 쓴다 — 기존 series 에 uid tag 가 추가된다
// (Influx 의 series 식별은 measurement + tags 의 조합이므로, 같은 timestamp 의
// 같은 다른 tag 조합에 uid 가 추가된다 — 운영자는 사전에 staging 확인 필수).
const fluxQueryTemplate = `// Backfill: device_id %q -> uid %q
// Affected measurements: %s
// Tag key: %q
from(bucket: %q)
  |> range(start: 0)
  |> filter(fn: (r) => r[%q] == %q)
  |> map(fn: (r) => ({ r with uid: %q }))
  |> to(bucket: %q)

`

// GenerateFluxScript 는 ClassifyResult 의 Mapped entries 로 Flux 스크립트를 작성한다.
//
// 결과는 결정론 — 동일 입력에 대해 항상 동일 byte 출력.
func GenerateFluxScript(w io.Writer, bucket, org string, result ClassifyResult, generatedAt time.Time) error {
	header := fmt.Sprintf(fluxScriptHeader,
		generatedAt.UTC().Format(time.RFC3339),
		bucket,
		org,
		result.MappedCount(),
	)
	if _, err := io.WriteString(w, header); err != nil {
		return fmt.Errorf("Flux header 쓰기 실패: %w", err)
	}

	for _, m := range result.Mapped {
		measurements := strings.Join(m.Measurements, ", ")
		block := fmt.Sprintf(fluxQueryTemplate,
			m.Composite,
			m.UUID,
			measurements,
			m.TagKey,
			bucket,
			m.TagKey,
			m.Composite,
			m.UUID,
			bucket,
		)
		if _, err := io.WriteString(w, block); err != nil {
			return fmt.Errorf("Flux query 쓰기 실패 (%s): %w", m.Composite, err)
		}
	}
	return nil
}
