// script_v3.go — InfluxDB v3 (SQL / InfluxQL) backfill 스크립트 생성.
//
// InfluxDB v3 의 데이터 모델은 v2 와 본질적으로 다르다:
//   - v2 는 Flux 의 `to()` 로 동일 series 에 tag 추가가 가능했다.
//   - v3 는 line-protocol 기반의 immutable points 모델 — UPDATE 가 없다.
//
// 따라서 v3 의 backfill 은 다음 두 가지 단계가 필요하다 (운영자 책임):
//  1. 영향 받는 row 식별: SQL SELECT.
//  2. 새 row 작성: 원본 timestamp + 모든 tag/field + 추가된 uid tag 를
//     line protocol 로 다시 write (influx3 CLI 또는 API).
//
// 본 도구는 1번 단계의 SELECT 스크립트와 2번 단계의 운영자 가이드 (RUN.md) 를
// 생성한다. 실제 line-protocol re-write 는 운영자가 자체 도구로 수행한다.
//
// 사용 가능한 대안 (운영자 선택):
//   - InfluxDB v3 의 SQL 에 추가된 INSERT INTO ... SELECT (제한적).
//   - 외부 ETL 도구 (Telegraf, Vector 등) 로 query → transform → write.
//   - influx3 CLI 의 query + write 조합.
package tsdbtags

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// sqlScriptHeader 는 생성된 .sql 파일의 상단 주석 (운영자 안내).
const sqlScriptHeader = `-- Generated by xflowd migrate tsdb-tags (Phase C § C2)
-- SPEC-DEVICE-IDENTITY-001 — device_id (composite) -> uid (UUID) backfill
--
-- IMPORTANT (InfluxDB v3 backfill):
--   - InfluxDB v3 has NO native UPDATE for tags.
--   - This script SELECTs affected rows. Operator MUST re-write rows
--     with additional 'uid' tag using line-protocol (influx3 CLI / API).
--   - See RUN.md (in this output directory) for detailed procedure.
--   - Run in STAGING first.
--
-- Generated at: %s
-- Target: InfluxDB v3 (SQL / InfluxQL)
-- Database: %s
--
-- Mappings: %d composite -> uid pairs

`

// sqlSelectTemplate 는 단일 composite 변환을 위한 SELECT 블록이다.
//
// `*` 대신 모든 column 을 명시적으로 나열할 수도 있으나, 본 도구는 schema 의
// 모든 column 을 캡처하기 위해 `SELECT *` 를 사용한다 (운영자가 후속 처리).
const sqlSelectTemplate = `-- Backfill: device_id %q -> uid %q
-- Affected measurements: %s
-- Tag key: %q
-- Step 1: Identify affected rows (review before re-writing with uid tag).
%s
`

// GenerateSQLScript 는 ClassifyResult 의 Mapped entries 로 v3 SELECT 스크립트를 작성한다.
//
// 각 measurement 마다 별도 SELECT 를 생성한다 (v3 의 SQL 은 measurement 가 table 명).
func GenerateSQLScript(w io.Writer, database string, result ClassifyResult, generatedAt time.Time) error {
	header := fmt.Sprintf(sqlScriptHeader,
		generatedAt.UTC().Format(time.RFC3339),
		database,
		result.MappedCount(),
	)
	if _, err := io.WriteString(w, header); err != nil {
		return fmt.Errorf("SQL header 쓰기 실패: %w", err)
	}

	for _, m := range result.Mapped {
		// 각 measurement 마다 별도 SELECT — v3 에서 measurement 는 table 이다.
		var selects []string
		for _, meas := range m.Measurements {
			selects = append(selects,
				fmt.Sprintf("SELECT * FROM %q WHERE %q = '%s';",
					meas,
					m.TagKey,
					sqlEscapeSingleQuotes(m.Composite),
				),
			)
		}
		measurementsList := strings.Join(m.Measurements, ", ")
		block := fmt.Sprintf(sqlSelectTemplate,
			m.Composite,
			m.UUID,
			measurementsList,
			m.TagKey,
			strings.Join(selects, "\n"),
		)
		if _, err := io.WriteString(w, block); err != nil {
			return fmt.Errorf("SQL select 쓰기 실패 (%s): %w", m.Composite, err)
		}
		if _, err := io.WriteString(w, "\n"); err != nil {
			return fmt.Errorf("SQL 줄바꿈 쓰기 실패: %w", err)
		}
	}
	return nil
}

// sqlEscapeSingleQuotes 는 SQL literal 의 single quote 를 두 개로 escape 한다.
//
// composite key 는 보통 `agent:local_id` 의 안전한 문자만 포함하지만, 보수적으로 escape.
func sqlEscapeSingleQuotes(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

// readmeTemplate 는 운영자 실행 가이드 (RUN.md) 의 본문 템플릿이다.
const readmeTemplate = `# tsdb-tags 마이그레이션 실행 가이드 (Phase C § C2)

본 디렉토리는 ` + "`xflowd migrate tsdb-tags`" + ` 가 생성한 InfluxDB backfill 스크립트와
운영자 실행 가이드를 포함합니다.

> Generated at: %s
> Target: %s
> Bucket/Database: %s
> Mappings: %d composite -> uid

## 0. 안전 원칙

- **사전 백업 필수**: InfluxDB 백업 (snapshot, dump) 을 먼저 수행하세요.
- **staging 우선**: production 적용 전 staging 환경에서 동일 스크립트로 리허설.
- **모니터링**: 실행 중 Influx 의 부하 + 쿼리 결과 확인.
- **롤백 가능성**: 백업에서 복원 가능 — 운영자가 별도 검증 절차 보유.

## 1. 사전 점검 (Pre-flight)

다음을 확인하세요:

- [ ] InfluxDB 인스턴스 백업 완료 (스냅샷 / dump).
- [ ] staging 환경에서 동일 스크립트 dry-run 또는 실행 완료 후 검증.
- [ ] 클러스터 부하 여유 (peak time 회피).
- [ ] device_ids.json 매핑이 최신 (생성 시점과 production 시점이 일치).
- [ ] 본 디렉토리의 스크립트를 ` + "`diff`" + ` / 코드 리뷰로 검토.

%s

## 2. 실행 절차

%s

## 3. 검증

%s

## 4. 롤백

마이그레이션 결과가 만족스럽지 않으면:

1. xflowd 데몬 중지 (` + "`systemctl stop xflowd`" + ` 등).
2. InfluxDB 사전 백업에서 데이터 복원.
3. xflowd 데몬 재시작.

## 5. 다음 단계 (C3 — Dual-tag 기간 운영)

C2 backfill 이 완료되면 xflowd 데몬은 새 데이터를 두 tag (id + uid) 모두로
기록해야 합니다. 이는 SPEC-DEVICE-IDENTITY-001 Phase C § C3 의 책임으로,
별도 PR 시리즈에서 진행됩니다.

## 부록: 본 디렉토리의 파일 구조

`

// v2RunSection 은 v2 의 실행 가이드 본문이다.
const v2RunSection = `### v2 (Flux) 실행

` + "```bash" + `
# 1. Flux 스크립트 검토
less migration-v2.flux

# 2. staging 에서 dry-run 시뮬레이션 (옵션 — Flux 에는 표준 dry-run 이 없음)
#    influx query --org <ORG> --token <READ_TOKEN> --file migration-v2.flux

# 3. production 실행 (write 권한 토큰 필요)
influx query \
  --org <ORG> \
  --token <WRITE_TOKEN> \
  --file migration-v2.flux

# 4. 진행 상황 모니터링 (별도 터미널)
influx query 'from(bucket: "%s") |> range(start: -1h) |> count()'
` + "```"

// v3RunSection 은 v3 의 실행 가이드 본문이다 (line-protocol re-write 절차 강조).
const v3RunSection = "### v3 (SQL / InfluxQL) 실행\n\n" +
	"InfluxDB v3 는 tag UPDATE 를 지원하지 않으므로 **line-protocol re-write** 가 필요합니다:\n\n" +
	"```bash\n" +
	"# 1. SELECT 스크립트 검토\n" +
	"less migration-v3.sql\n" +
	"\n" +
	"# 2. 영향 row 확인 (read-only)\n" +
	"influx3 query --database %s --file migration-v3.sql\n" +
	"\n" +
	"# 3. (운영자 자체) 각 row 를 line-protocol 로 재작성 — 다음 단계 필요:\n" +
	"#    a. SELECT 결과를 JSON / CSV 로 dump\n" +
	"#    b. 각 row 에 uid 태그 추가\n" +
	"#    c. influx3 write 로 다시 ingest (line-protocol)\n" +
	"#    예시 (Telegraf, Vector, 자체 스크립트):\n" +
	"#      influx3 write --database %s --file rewritten.lp\n" +
	"```\n" +
	"\n" +
	"> 본 도구는 SELECT 단계만 자동화합니다. line-protocol re-write 는 운영자가\n" +
	"> 환경에 맞는 도구 (Telegraf transform, custom script 등) 로 수행합니다.\n" +
	"> v3 native INSERT INTO ... SELECT 지원 여부는 운영 시점의 InfluxDB v3\n" +
	"> 버전 문서를 확인하세요."

// v2VerifySection 은 v2 의 검증 쿼리이다.
const v2VerifySection = `실행 후 검증 (Flux):

` + "```flux" + `
// uid tag 가 추가된 series 수 확인
from(bucket: "%s")
  |> range(start: 0)
  |> filter(fn: (r) => exists r.uid)
  |> group(columns: ["uid"])
  |> count()
` + "```"

// v3VerifySection 은 v3 의 검증 쿼리이다.
const v3VerifySection = `실행 후 검증 (SQL):

` + "```sql" + `
-- uid 가 채워진 row 수 확인
SELECT COUNT(*) AS rows_with_uid
FROM <measurement>
WHERE uid IS NOT NULL;
` + "```"

// GenerateReadme 는 운영자 실행 가이드 RUN.md 를 생성한다.
//
// includesSection 은 출력 디렉토리 의 파일 목록 (예: migration-v2.flux, RUN.md 등).
func GenerateReadme(
	w io.Writer,
	target Target,
	database string,
	mappedCount int,
	generatedAt time.Time,
	includesSection string,
) error {
	var runSection, verifySection string
	switch target {
	case TargetV2:
		runSection = fmt.Sprintf(v2RunSection, database)
		verifySection = fmt.Sprintf(v2VerifySection, database)
	case TargetV3:
		runSection = fmt.Sprintf(v3RunSection, database, database)
		verifySection = v3VerifySection
	default:
		return fmt.Errorf("RUN.md 생성: 알 수 없는 target %q", target)
	}

	header := fmt.Sprintf(readmeTemplate,
		generatedAt.UTC().Format(time.RFC3339),
		string(target),
		database,
		mappedCount,
		"## (운영자 사전 검토 체크리스트 끝)",
		runSection,
		verifySection,
	)
	if _, err := io.WriteString(w, header); err != nil {
		return fmt.Errorf("RUN.md header 쓰기 실패: %w", err)
	}
	if _, err := io.WriteString(w, includesSection); err != nil {
		return fmt.Errorf("RUN.md file 목록 쓰기 실패: %w", err)
	}
	return nil
}
